name: Build-E2E

on:
  push:
    branches:
      - "**"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
         node-version: 18
         cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Build for production
        run: pnpm build

  E2E:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Repo
         uses: actions/checkout@v3

       - name: Use PNPM
         uses: pnpm/action-setup@v2.2.4
         with:
            version: latest

       - name: Use Node.js 18
         uses: actions/setup-node@v3
         with:
          node-version: 18
          cache: "pnpm"

       - name: Install Playwright Browsers
         run: pnpx playwright install --with-deps

       - name: Install
         run: pnpm install

       - name: Run tests
         run: pnpm test
env:
  NEXT_PUBLIC_UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
  NEXT_PUBLIC_UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
